### ISSUE TITLE
clairifcation

### ISSUE THREAD

**Issue by timm** [ai-se/HOW1#30]
you used cliffsdelta counts to genera fig9 

but for the ranks show at left, you used AI2+ bootstrap?

**Comment by rahlk** [comment]
Yup that's correct.

**Comment by timm** [comment]
thats.... adherent.  A12 to score cliffs delta values. 

why did u do it that way? a simpler, clear, faster to explain if you showed the raw performance predictions (runtimes for seigmund and defects for Juresko) and then run bootstrap+A12 (via scott knott) on those scores
