### ISSUE TITLE
Apache.pdf DDBJ.pdf

### ISSUE THREAD

**Issue by timm** [ai-se/HOW1#31]
i want to use these figures to argue for different exemplar policies. 

how long would i take you to regenerate these with:
- feature wight= true, info prune 50% of the attributes, and then
- black = baseline
- green = using the best instance in the cluster as the exemplar
- red = using the median instance in the cluster as the exemplar

also, when you redo these graphs, Bigger fonts!

**Comment by rahlk** [comment]
Probably around 2-3 hrs tops

**Comment by timm** [comment]
also, black line: is that ACTUAL or PREDICTED? should be PREDICTED, right?

**Comment by timm** [comment]
Also, the figure names need to match the text. 

is it SQL or SQLite?

our Berkely DBs are DBCE DBJE. so what is BDBC and BDBJ (blow job? i dont thing so)

in the paper we are saying x264 not X264. which is it?

**Comment by rahlk** [comment]
BDBJ is Berkley DB Java
BDBC is Berkeley DB C

I'll match the names to the text in the new figures.

**Comment by rahlk** [comment]
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item
